Description of atdisplay
atdisplay
PURPOSE
ATDISPLAY checks the verbosity level in the global variable GLOBVAL
SYNOPSIS
function atdisplay(verbosity,message)
DESCRIPTION
ATDISPLAY checks the verbosity level in the global variable GLOBVAL
          and displays message if this is greater than the verbosity
          for this message.
  See also NUMDIFPARAMS
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atcavityoff ATCAVITYOFF switches cavities off
atcavityon ATRADON switches RF cavities on
atradon ATRADON switches RF and radiation on
SOURCE CODE
function atdisplay(verbosity,message)
%ATDISPLAY checks the verbosity level in the global variable GLOBVAL
%          and displays message if this is greater than the verbosity
%          for this message.
%
%  See also NUMDIFPARAMS
global GLOBVAL
if isfield(GLOBVAL,'verbosity')&& verbosity<= GLOBVAL.verbosity
    disp(message)
end
GitHub Website at © 2018