Description of atroot
atroot
PURPOSE
ATROOT returns Accelerator Toolbox root directory
SYNOPSIS
function rootdir = atroot
DESCRIPTION
ATROOT returns Accelerator Toolbox root directory
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
athelp ATHELP generates the list of Accelerator Toolbox functions
atm2html MAKEDOC_HTML - Generate new MML, SOLEIL and AT HTML help files
atmexall ATMEXALL builds all AT platform dependent mex-files from C-sources
atupdateContents Updates Contents.m of AT directories
SOURCE CODE
function rootdir = atroot
%ATROOT returns Accelerator Toolbox root directory
[pdir, pname, pext] = fileparts(which(mfilename));
rootdir = fullfile(pdir,'');