Description of decodeatargs
decodeatargs
PURPOSE
DECODEATARGS separates arguments and resources
SYNOPSIS
function [rsrc,varargout] = decodeatargs(default_values,args)
DESCRIPTION
DECODEATARGS separates arguments and resources
  [RSRC,ARGS]=decodeatargs(DEFARGS,ARGLIST)
  INPUTS
    1. DEFARGS - Values per default if not specify for mandatory
                 argument
    2. ARGS    - Other arugments
  OUPUTS
    1. rsrc      - Mandatory arguments
    2. varargout - Optional arguments
  NOTES
    1. DEFARGS must have length >= 2
  See also getoption, getflag
CROSS-REFERENCE INFORMATION
This function calls:
parseargs PARSEARGS Check and expands optional argument lists
This function is called by:
atM66 ATM66(FAMNAME,M66,PASSMETHOD)
atM66Tijk ATM66(FAMNAME,M66,Tijk,PASSMETHOD)
atQuantDiff atQuantDiff creates a quantum diffusion element
ataperture ATAPERTURE Creates a aperture element
atcorrector ATCORRECTOR Creates a drift space element with class 'Corrector'
atdrift ATDRIFT Creates a drift space element with Class 'Drift'
atmarker ATMARKER Creates a marker space element
atmonitor ATMONITOR Creates a Beam Position Monitor element with Class 'Monitor'
atmultipole ATMULTIPOLE Creates a multipole element
atquadrupole ATQUADRUPOLE Creates a quadrupole element with Class 'Quadrupole'
atrbend ATRBEND Creates a rectangular bending magnet element with class 'Bend'
atrfcavity ATRFCAVITY Creates an rfcavity element with Class 'RFCavity'
atringparam ATRINGPARAM Creates a RingParameter Element which should go at the beginning of the ring
atsbend ATSBEND Creates a sector bending magnet element with class 'Bend'
atsextupole ATSEXTUPOLE Creates a sextupole element with class 'Sextupole'
atskewquad ATSKEWQUAD Creates a skew quadrupole element with Class 'Multipole'
atsolenoid ATSOLENOID Creates a new solenoid element with Class 'Solenoid'
atthinmultipole ATTHINMULTIPOLE Creates a thin multipole element
SOURCE CODE
function [rsrc,varargout] = decodeatargs(default_values,args)
%DECODEATARGS separates arguments and resources
%
%  [RSRC,ARGS]=decodeatargs(DEFARGS,ARGLIST)
%
%  INPUTS
%    1. DEFARGS - Values per default if not specify for mandatory
%                 argument
%    2. ARGS    - Other arugments
%
%  OUPUTS
%    1. rsrc      - Mandatory arguments
%    2. varargout - Optional arguments
%
%  NOTES
%    1. DEFARGS must have length >= 2
%
%  See also getoption, getflag
% function to get the first string which is after the PassMethod
nopass    = @(arg) ischar(arg) && ~isempty(arg) && isempty(regexp(arg,'.*Pass$','once'));
% get index of first optional char Argument
chararg   = find(cellfun(nopass,[args {'x'}]),1);
% get all optional argument (ressources)
rsrc      = args(chararg:end);
% output mandatory argument
varargout = parseargs(default_values,args(1:chararg-1));
end