Description of testTrackBBR
testTrackBBR
PURPOSE
create a fast ring from ESRF lattice
SYNOPSIS
This is a script file.
DESCRIPTION
create a fast ring from ESRF lattice
generate a Broad Band Resonator Impedance
add to fast ring
CROSS-REFERENCE INFORMATION
This function calls:
makeFastRingWithBBR SI units
atbeam ATBEAM generates a particle distribution according to a sigma matrix
atsigma ATSIGMA constructs a beam sigma matrix 2x2 4x4 or 6x6
ringpass RINGPASS tracks particles through each element of the cell array RING
esrf
This function is called by:
SOURCE CODE
%create a fast ring from ESRF lattice
%generate a Broad Band Resonator Impedance
%add to fast ring
makeFastRingWithBBR;
%Generate particle distribution and track
%watch rms values
NP=1e4;
Nturns=1000;
particles=atbeam(NP,atsigma(esrf));
disp(std(particles'))
for i=1:Nturns
  particles=ringpass(fastringBBR,particles,1);
  disp(std(particles'))
end