Description of findorbit6Err
findorbit6Err
PURPOSE
findorbit6 with bpm reading errors
SYNOPSIS
function orbit = findorbit6Err(RING, indbpm,varargin)
DESCRIPTION
 findorbit6 with bpm reading errors
see also findorbit6 bpm_process bpm_matrices
CROSS-REFERENCE INFORMATION
This function calls:
findorbit6 FINDORBIT6 finds closed orbit in the full 6-d phase space
bpm_matrices BPM_MATRICES Computes the transformation matrices for the given BPMs
bpm_process UNTITLED3 Summary of this function goes here
This function is called by:
atdispersionfreesteering function [...
testdispersionfreesteering test errors and correction functions
atRFcorrection function [...
testsetRFCavityErr test errors and correction functions
DisplayCorrectionEffect [d0,de,dc]=DisplayCorrectionEffect(...
atcorrectorbit
testorbitbump test errors and correction functions
testorbitcorrection test errors and correction functions
BumpAtBPM function roff=BumpAtBPM(...
findrespmat FINDRESPM_mod computes the change in the closed orbit due to parameter perturbations
getresponsematrices
atfirstturntrajectory ATFIRSTTURNTRAJECTORY Makes first turn correction
finddispersion6Err FINDDISPERSION6ERR Gets 6D dispersion with bpm reading errors
SOURCE CODE
function orbit = findorbit6Err(RING, indbpm,varargin)
% findorbit6 with bpm reading errors
%
%see also findorbit6 bpm_process bpm_matrices
orbit = findorbit6(RING, indbpm, varargin{:});
% BPM errors used only if class is Monitor
%useind=ismember(indbpm,find(atgetcells(ring,'Class','Monitor')));
useind=1:length(indbpm);
[rel,tel,trand] = bpm_matrices(RING(indbpm(useind)));
bpmreading = bpm_process(orbit([1,3],:),rel,tel,trand);
orbit(1,:)=bpmreading(1,:);
orbit(3,:)=bpmreading(2,:);
return
GitHub Website at © 2018