Description of finddispersion6Err
finddispersion6Err
PURPOSE
FINDDISPERSION6ERR Gets 6D dispersion with bpm reading errors
SYNOPSIS
function dispersion=finddispersion6Err(RING, indbpm,indrfc,alpha,delta,inCOD)
DESCRIPTION
FINDDISPERSION6ERR Gets 6D dispersion with bpm reading errors
  See also findorbit6Err
CROSS-REFERENCE INFORMATION
This function calls:
atsetfieldvalues ATSETFIELDVALUES sets the field values of MATLAB cell array of structures
findorbit6Err findorbit6 with bpm reading errors
This function is called by:
atdispersionfreesteering function [...
testdispersionfreesteering test errors and correction functions
atQuadRDTdispersioncorrection ATQUADRDTDISPERSIONCORRECTION - Make dispersion correction based on RDTs
atRDTdispersioncorrection ATRDTDISPERSIONCORRECTION Makes dispersion correction based on RDTs
atRDTdispersionmeasuredcorrection ATRDTDISPERSIONMEASUREDCORRECTION Makes correction of dispersion based on
atSkewRDTdispersioncorrection function [...
DisplayCorrectionEffect [d0,de,dc]=DisplayCorrectionEffect(...
atcorrectdispersion function [...
testdispersioncorrection test errors and correction functions
findrespmat FINDRESPM_mod computes the change in the closed orbit due to parameter perturbations
getresponsematrices
SOURCE CODE
function dispersion=finddispersion6Err(RING, indbpm,indrfc,alpha,delta,inCOD)
%FINDDISPERSION6ERR Gets 6D dispersion with bpm reading errors
%
%  See also findorbit6Err
f0=RING{indrfc(1)}.Frequency;
% plus delta
RINGp=atsetfieldvalues(RING,indrfc,'Frequency',f0-alpha*(+delta)*f0);
orbitp = findorbit6Err(RINGp, indbpm, inCOD);
RINGm=atsetfieldvalues(RING,indrfc,'Frequency',f0-alpha*(-delta)*f0);
orbitm = findorbit6Err(RINGm, indbpm, inCOD);
dispersion=(orbitp-orbitm)/2/delta;
end
GitHub Website at © 2018