Description of run_matchChromaticity
run_matchChromaticity
PURPOSE
match chrmaticity
SYNOPSIS
This is a script file.
DESCRIPTION
  match chrmaticity
CROSS-REFERENCE INFORMATION
This function calls:
atVariableBuilder atVarBuilder create a simple variable structure for use with atmatch
atlinconstraint ATLINCONSTRAINT Generate a constraint on linear optics for atmatch
atmatch function [...
This function is called by:
SOURCE CODE
%  match chrmaticity
load dba.mat
variabsxt=atVariableBuilder(RING,{'SF','SD'},{{'PolynomB',{1,3}}});
ConstrChrom=[...
    atlinconstraint(1,{{'chromaticity',{1}}},0,0,1)...
    atlinconstraint(1,{{'chromaticity',{2}}},0,0,1)];
tol=1e-8;
RINGchrom0=atmatch(RING,variabsxt,ConstrChrom,tol,1000,4);