Description of ataperture
ataperture
PURPOSE
ATAPERTURE Creates a aperture element
SYNOPSIS
function elem=ataperture(fname,varargin)
DESCRIPTION
ATAPERTURE Creates a aperture element
 ATAPERTURE(FAMNAME,LIMITS,PASSMETHOD
 define physical aperture element (collimator)
 lim=[-x,+x,-y,+y];
 lim={[-x,+x,-y,+y],[-x,+x,-y,+y],[-x,+x,-y,+y],...};
 will generate various aperture elements (one for every set of errors)
  See also setphysicalaperture
CROSS-REFERENCE INFORMATION
This function calls:
atbaselem ATBASELEM Create an AT element structure + various checks
decodeatargs DECODEATARGS separates arguments and resources
getoption GETOPTION Extract a keyword argument from the input arguments
This function is called by:
aperture APERTURE Creates a aperture element in old a AT version (Obsolete)
at2py ELSTR=AT2PY(ELEM) convert AT element tp pyat
at2str AT2STR Makes the string representation of an AT element
SetPhysicalAperture ringapert=SetPhysicalAperture(ring,apertureX,apertureY)
australian_synchrotron
SOURCE CODE
function elem=ataperture(fname,varargin)
%ATAPERTURE Creates a aperture element
% ATAPERTURE(FAMNAME,LIMITS,PASSMETHOD
% define physical aperture element (collimator)
% lim=[-x,+x,-y,+y];
%
% lim={[-x,+x,-y,+y],[-x,+x,-y,+y],[-x,+x,-y,+y],...};
% will generate various aperture elements (one for every set of errors)
%
%  See also setphysicalaperture
%
[rsrc,limits,method,~]=decodeatargs({[0 0],'AperturePass',''},varargin);
[limits,rsrc]=getoption(rsrc,'Limits',limits);
[method,rsrc]=getoption(rsrc,'PassMethod',method);
[cl,rsrc]=getoption(rsrc,'Class','Aperture');
elem=atbaselem(fname,method,'Class',cl,'Limits',limits,rsrc{:});
end