Description of atcorrector
atcorrector
PURPOSE
ATCORRECTOR Creates a drift space element with class 'Corrector'
SYNOPSIS
function elem=atcorrector(fname,varargin)
DESCRIPTION
ATCORRECTOR Creates a drift space element with class 'Corrector'
  atcorrector(FAMNAME,LENGTH,KICK,PASSMETHOD)
  INPUTS
  1. FAMNAME        family name
  2. LENGTH        length [m]
  3. KICK        [hor. kick, vert. kick] [rad]
  4. PASSMETHOD  tracking function, defaults to 'CorrectorPass'
  OUTPUTS
  1. ELEM - Structure with the AT element
  EXAMPLES
  1. Each pair {'FIELDNAME',VALUE} is added to the element
  NOTES
  1. Fieldname can be called by calling the passmethod
     [req opt] = CorrectorPass
                 where req are mandatory field and opt are optional fields
  See also atquadrupole, atsextupole, atsbend, atrbend
           atmultipole, atthinmultipole, atmarker
CROSS-REFERENCE INFORMATION
This function calls:
atbaselem ATBASELEM Create an AT element structure + various checks
decodeatargs DECODEATARGS separates arguments and resources
getoption GETOPTION Extract a keyword argument from the input arguments
This function is called by:
run_BumpFit fit a bump using correctors
at2py ELSTR=AT2PY(ELEM) convert AT element tp pyat
at2str AT2STR Makes the string representation of an AT element
atelem ATELEM makes a new AT element structure from another element,
atreadbeta ATREADBETA reads a BETA file
australian_synchrotron
soleil SOLEIL Loads SOLEIL lattice
thomx
SOURCE CODE
function elem=atcorrector(fname,varargin)
%ATCORRECTOR Creates a drift space element with class 'Corrector'
%
%  atcorrector(FAMNAME,LENGTH,KICK,PASSMETHOD)
%
%  INPUTS
%  1. FAMNAME        family name
%  2. LENGTH        length [m]
%  3. KICK        [hor. kick, vert. kick] [rad]
%  4. PASSMETHOD  tracking function, defaults to 'CorrectorPass'
%
%  OUTPUTS
%  1. ELEM - Structure with the AT element
%
%  EXAMPLES
%  1. Each pair {'FIELDNAME',VALUE} is added to the element
%
%  NOTES
%  1. Fieldname can be called by calling the passmethod
%     [req opt] = CorrectorPass
%                 where req are mandatory field and opt are optional fields
%
%  See also atquadrupole, atsextupole, atsbend, atrbend
%           atmultipole, atthinmultipole, atmarker
% Input parser for option
[rsrc,L,kick,method] = decodeatargs({0,[0 0],'CorrectorPass'},varargin);
[L,rsrc]             = getoption(rsrc,'Length',L);
[kick,rsrc]          = getoption(rsrc,'KickAngle',kick);
[method,rsrc]        = getoption(rsrc,'PassMethod',method);
[cl,rsrc]            = getoption(rsrc,'Class','Corrector');
% Build the element
elem = atbaselem(fname,method,'Class',cl,'Length',L,'KickAngle',kick,rsrc{:});
end
GitHub Website at © 2018