Description of atdampMatElem
atdampMatElem
PURPOSE
atdampMatElem creates an element that applies the global damping matrix
SYNOPSIS
function elem=atdampMatElem(fname,ring,varargin)
DESCRIPTION
   atdampMatElem creates an element that applies the global damping matrix
ELEM=ATDAMPMATELEM(FAMNAME,RING,CAVIPASS,BENDPASS,QUADPASS)
FAMNAME:   family name
RING:        initial AT structure, without radiation passmethods
CAVIPASS:    pass method for cavities (default ThinCavityPass)
BENDPASS:    pass method for bending magnets. Special values:
           '' makes no change,
           'auto' wille substitute 'Pass' with 'RadPass' in any method
           (default: 'auto')
QUADPASS:    pass method for quadrupoles
           '' makes no change,
           'auto' wille substitute 'Pass' with 'RadPass' in any method
           (default: '')
CROSS-REFERENCE INFORMATION
This function calls:
findm66 FINDM66 numerically finds the 6x6 transfer matrix of an accelerator lattice
atradon ATRADON switches RF and radiation on
atM66 ATM66(FAMNAME,M66,PASSMETHOD)
This function is called by:
SOURCE CODE
function elem=atdampMatElem(fname,ring,varargin)
%   atdampMatElem creates an element that applies the global damping matrix
%ELEM=ATDAMPMATELEM(FAMNAME,RING,CAVIPASS,BENDPASS,QUADPASS)
%
%FAMNAME:   family name
%RING:        initial AT structure, without radiation passmethods
%CAVIPASS:    pass method for cavities (default ThinCavityPass)
%BENDPASS:    pass method for bending magnets. Special values:
%           '' makes no change,
%           'auto' wille substitute 'Pass' with 'RadPass' in any method
%           (default: 'auto')
%QUADPASS:    pass method for quadrupoles
%           '' makes no change,
%           'auto' wille substitute 'Pass' with 'RadPass' in any method
%           (default: '')
%
ringrad=atradon(ring,varargin{:});
m66_norad=findm66(ring);
m66_rad=findm66(ringrad);
elem=atM66(fname,m66_norad\m66_rad);
end