Description of atdrift
atdrift
PURPOSE
ATDRIFT Creates a drift space element with Class 'Drift'
SYNOPSIS
function elem=atdrift(fname,varargin)
DESCRIPTION
ATDRIFT Creates a drift space element with Class 'Drift'
atdrift(famname,length,passmethod)
  INPUTS
  1. famname       - Family name
  2. length       - Length [m]
  3. passmethod   - Tracking function, defaults to 'driftpass'
  OPTIONS (order does not matter)
    R1                6 x 6 rotation matrix at the entrance
     R2                6 x 6 rotation matrix at the entrance
     T1                6 x 1 translation at entrance
     T2                6 x 1 translation at exit
     NumIntSteps    Number of integration steps
     MaxOrder       Max Order for multipole (1 up to quadrupole)
  OUTPUTS
  1. ELEM - Structure with the AT element
  EXAMPLES
  1. atdrift(famname,length,passmethod,'fieldname1',value1,...)
    each pair {'fieldname',value} is added to the element
  See also  atquadrupole, atsextupole, atsbend, atrbend
            atmultipole, atthinmultipole, atmarker, atcorrector
CROSS-REFERENCE INFORMATION
This function calls:
atbaselem ATBASELEM Create an AT element structure + various checks
decodeatargs DECODEATARGS separates arguments and resources
getoption GETOPTION Extract a keyword argument from the input arguments
This function is called by:
drift DRIFT Creates a drift element in old a AT version (Obsolete)
buildATLattice given a list (cell array) of elements with specified field Spos (center of element (madx default)) in a
at2py ELSTR=AT2PY(ELEM) convert AT element tp pyat
at2str AT2STR Makes the string representation of an AT element
atelem ATELEM makes a new AT element structure from another element,
atundulator define undulator model
atreadbeta ATREADBETA reads a BETA file
FODO
australian_synchrotron
dba create dba lattice
esrf
soleil SOLEIL Loads SOLEIL lattice
thomx
SOURCE CODE
function elem=atdrift(fname,varargin)
%ATDRIFT Creates a drift space element with Class 'Drift'
%atdrift(famname,length,passmethod)
%
%  INPUTS
%  1. famname       - Family name
%  2. length       - Length [m]
%  3. passmethod   - Tracking function, defaults to 'driftpass'
%
%  OPTIONS (order does not matter)
%    R1                6 x 6 rotation matrix at the entrance
%     R2                6 x 6 rotation matrix at the entrance
%     T1                6 x 1 translation at entrance
%     T2                6 x 1 translation at exit
%     NumIntSteps    Number of integration steps
%     MaxOrder       Max Order for multipole (1 up to quadrupole)
%
%  OUTPUTS
%  1. ELEM - Structure with the AT element
%
%  EXAMPLES
%  1. atdrift(famname,length,passmethod,'fieldname1',value1,...)
%    each pair {'fieldname',value} is added to the element
%
%  See also  atquadrupole, atsextupole, atsbend, atrbend
%            atmultipole, atthinmultipole, atmarker, atcorrector
[rsrc,L,method]=decodeatargs({0,'DriftPass'},varargin);
[L,rsrc]=getoption(rsrc,'Length',L);
[method,rsrc]=getoption(rsrc,'PassMethod',method);
[cl,rsrc]=getoption(rsrc,'Class','Drift');
elem=atbaselem(fname,method,'Class',cl,'Length',L,rsrc{:});
end