Description of atM66Tijk
atM66Tijk
PURPOSE
ATM66(FAMNAME,M66,Tijk,PASSMETHOD)
SYNOPSIS
function elem=atM66Tijk(fname,varargin)
DESCRIPTION
ATM66(FAMNAME,M66,Tijk,PASSMETHOD)
   atM66 creates an element that applies an arbitrary matrix m66
FAMNAME    family name
M66        transfer matrix, defaults to Identity(6)]
Tijk       2nd order transfer matrix, defaults to zeros(6,6,6)]
PASSMETHOD    tracking function, defaults to 'MatrixTijkPass'
ATM66(FAMNAME,ATSTRUCT,PASSMETHOD)
   atM66 will generate the matrix by calling FINDM66(ATSTRUCT)
ATSTRUCT   AT structure
CROSS-REFERENCE INFORMATION
This function calls:
findm66 FINDM66 numerically finds the 6x6 transfer matrix of an accelerator lattice
atbaselem ATBASELEM Create an AT element structure + various checks
decodeatargs DECODEATARGS separates arguments and resources
getoption GETOPTION Extract a keyword argument from the input arguments
This function is called by:
at2py ELSTR=AT2PY(ELEM) convert AT element tp pyat
at2str AT2STR Makes the string representation of an AT element
SOURCE CODE
function elem=atM66Tijk(fname,varargin)
%ATM66(FAMNAME,M66,Tijk,PASSMETHOD)
%   atM66 creates an element that applies an arbitrary matrix m66
%
%FAMNAME    family name
%M66        transfer matrix, defaults to Identity(6)]
%Tijk       2nd order transfer matrix, defaults to zeros(6,6,6)]
%PASSMETHOD    tracking function, defaults to 'MatrixTijkPass'
%
%ATM66(FAMNAME,ATSTRUCT,PASSMETHOD)
%   atM66 will generate the matrix by calling FINDM66(ATSTRUCT)
%
%ATSTRUCT   AT structure
[rsrc,m66,tijk,method]=decodeatargs({eye(6),zeros(6,6,6),'MatrixTijkPass'},varargin);
[method,rsrc]=getoption(rsrc,'PassMethod',method);
[cl,rsrc]=getoption(rsrc,'Class','MatrixTijkPass');
if isstruct(m66)
    m66=findm66(m66);
end
elem=atbaselem(fname,method,'Class',cl,'M66',m66,'Tijk',reshape(tijk,6,6,6),rsrc{:});