Description of atmonitor
atmonitor
PURPOSE
ATMONITOR Creates a Beam Position Monitor element with Class 'Monitor'
SYNOPSIS
function elem=atmonitor(fname,varargin)
DESCRIPTION
ATMONITOR Creates a Beam Position Monitor element with Class 'Monitor'
  INPUTS
  1. fname - Family name
  ATMONITOR(FAMNAME,'FIELDNAME1',VALUE1,...)
   Each pair {'FIELDNAME',VALUE} is added to the element
  See also atdrift, atsextupole, atsbend, atrbend
          atmultipole, atthinmultipole, atmarker, atcorrector
CROSS-REFERENCE INFORMATION
This function calls:
atbaselem ATBASELEM Create an AT element structure + various checks
decodeatargs DECODEATARGS separates arguments and resources
getoption GETOPTION Extract a keyword argument from the input arguments
This function is called by:
monitor MONITOR Creates a monitor element in old AT versions (Obsolete)
at2py ELSTR=AT2PY(ELEM) convert AT element tp pyat
at2str AT2STR Makes the string representation of an AT element
atreadbeta ATREADBETA reads a BETA file
australian_synchrotron
esrf
thomx
SOURCE CODE
function elem=atmonitor(fname,varargin)
%ATMONITOR Creates a Beam Position Monitor element with Class 'Monitor'
%
%  INPUTS
%  1. fname - Family name
%
%  ATMONITOR(FAMNAME,'FIELDNAME1',VALUE1,...)
%   Each pair {'FIELDNAME',VALUE} is added to the element
%
%  See also atdrift, atsextupole, atsbend, atrbend
%          atmultipole, atthinmultipole, atmarker, atcorrector
[rsrc,method,~]=decodeatargs({'IdentityPass',''},varargin);
[method,rsrc]=getoption(rsrc,'PassMethod',method);
[cl,rsrc]=getoption(rsrc,'Class','Monitor');
elem=atbaselem(fname,method,'Class',cl,rsrc{:});
end
GitHub Website at © 2018