Description of atsextupole
atsextupole
PURPOSE
ATSEXTUPOLE Creates a sextupole element with class 'Sextupole'
SYNOPSIS
function elem=atsextupole(fname,varargin)
DESCRIPTION
ATSEXTUPOLE Creates a sextupole element with class 'Sextupole'
  ATSEXTUPOLE(FAMNAME,LENGTH,S,PASSMETHOD)
  INPUTS
     1. FNAME            family name
    2. LENGTH            length [m]
    3. S                strength [m-2]
    4. PASSMETHOD     tracking function, defaults to 'StrMPoleSymplectic4Pass'
  OPTIONS (order does not matter)
    R1                6 x 6 rotation matrix at the entrance
     R2                6 x 6 rotation matrix at the entrance
     T1                6 x 1 translation at entrance
     T2                6 x 1 translation at exit
     NumIntSteps    Number of integration steps
     MaxOrder       Max Order for multipole (1 up to quadrupole)
  OUTPUTS
      1. ELEM - Structure with the AT element
  EXAMPLES
    ATSEXTUPOLE(FAMNAME,LENGTH,S,PASSMETHOD,'FIELDNAME1',VALUE1,...)
    Each pair {'FIELDNAME',VALUE} is added to the element
  See also: atdrift, atquadrupole, atmultipole, atsbend,
            atrbend,atskewquad, atmultipole, atthinmultipole, atmarker,
            atcorrector
CROSS-REFERENCE INFORMATION
This function calls:
atbaselem ATBASELEM Create an AT element structure + various checks
decodeatargs DECODEATARGS separates arguments and resources
getoption GETOPTION Extract a keyword argument from the input arguments
This function is called by:
sextupole SEXTUPOLE Creates a sextupole element in old AT versions (Obsolete)
at2py ELSTR=AT2PY(ELEM) convert AT element tp pyat
at2str AT2STR Makes the string representation of an AT element
atelem ATELEM makes a new AT element structure from another element,
atreadbeta ATREADBETA reads a BETA file
FODO
australian_synchrotron
dba create dba lattice
esrf
soleil SOLEIL Loads SOLEIL lattice
thomx
SOURCE CODE
function elem=atsextupole(fname,varargin)
%ATSEXTUPOLE Creates a sextupole element with class 'Sextupole'
%
%  ATSEXTUPOLE(FAMNAME,LENGTH,S,PASSMETHOD)
%
%  INPUTS
%     1. FNAME            family name
%    2. LENGTH            length [m]
%    3. S                strength [m-2]
%    4. PASSMETHOD     tracking function, defaults to 'StrMPoleSymplectic4Pass'
%
%  OPTIONS (order does not matter)
%    R1                6 x 6 rotation matrix at the entrance
%     R2                6 x 6 rotation matrix at the entrance
%     T1                6 x 1 translation at entrance
%     T2                6 x 1 translation at exit
%     NumIntSteps    Number of integration steps
%     MaxOrder       Max Order for multipole (1 up to quadrupole)
%
%  OUTPUTS
%      1. ELEM - Structure with the AT element
%
%  EXAMPLES
%    ATSEXTUPOLE(FAMNAME,LENGTH,S,PASSMETHOD,'FIELDNAME1',VALUE1,...)
%    Each pair {'FIELDNAME',VALUE} is added to the element
%
%  See also: atdrift, atquadrupole, atmultipole, atsbend,
%            atrbend,atskewquad, atmultipole, atthinmultipole, atmarker,
%            atcorrector
% Input parser for option
[rsrc,L,S,method] = decodeatargs({0,[],'StrMPoleSymplectic4Pass'},varargin);
[L,rsrc]          = getoption(rsrc,'Length',L);
[method,rsrc]     = getoption(rsrc,'PassMethod',method);
[PolynomB,rsrc]   = getoption(rsrc,'PolynomB',[0 0 0]);
[cl,rsrc]         = getoption(rsrc,'Class','Sextupole');
% Sextupole setting if not specified explicitly
if ~isempty(S), PolynomB(3)=S; end
% Build the element
elem=atbaselem(fname,method,'Class',cl,'Length',L,...
    'PolynomB',PolynomB,rsrc{:});
end
GitHub Website at © 2018