Description of findspos
findspos
PURPOSE
FINDSPOS returns longitudinal positions of accelerator lattice elements.
SYNOPSIS
function spos = findspos(line,refpts)
DESCRIPTION
FINDSPOS returns longitudinal positions of accelerator lattice elements.
  Return value is a row vector of positions S at the entrance of each
  element specified REFPTS (index list or logical mask)
 Note: REFPTS is an array of increasing indexes that
   select elements from range 1 to length(LATTICE)+1.
   REFPTS is allowed to go 1 point beyond the
   number of elements. In this case the last point is
   the EXIT of the last element. If LATTICE is a RING
   it is also the entrance of the first element after 1 turn.
   Note:
   1. Use findspos(RING,1:length(RING)) for to find
      longitudinal position of all elements
   2. Use findspos(LINE,length(LINE)+1) to find the
      total physical length
   3. If line is a closed ring, exit of the last element
      is also the entrance to the first.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ohmienvelopedemo OHMIENVELOPEDEMO illustrates the use of OHMIENVELOPE function
intlat INTLAT Interactive AT lattice editor
plotbeta PLOTBETA plots UNCOUPLED! beta-functions
atBunchLength bunch length due to the potential well effect
atsetcavity ATSECAVITY Sets the synchronous phase of the cavity assuming radiation
mcf MCF momentum compaction factor
computeRDT COMPUTERDT Computes Hamiltonian resonance driving terms (RDTs)
findorbit6 FINDORBIT6 finds closed orbit in the full 6-d phase space
plotcod PLOTCOD Closed Orbit Distortion
atlinopt ATLINOPT Performs linear analysis of the COUPLED lattices
atsummary ATSUMMARY - Prints out the paramters of the current AT lattice
linopt LINOPT performs linear analysis of the COUPLED lattices
ringpara RINGPARA Calculates various ring parameters
twissline TWISSLINE calculates linear optics functions for an UNCOUPLED transport line
twissring TWISSRING calculates linear optics functions for an UNCOUPLED ring
TouschekPiwinskiLifeTime function [Tl,contributionsTL]=TouschekPiwinskiLifeTime(r,dpp,Ib)
simpletestToucheckLT simple example of use of toucheck lifetime formula:
atbaseplot ATBASEPLOT Plots data generated by a user-supplied function
atplotsyn ATPLOTSYN Helper function for ATPLOT
plenvelope PLENVELOPE Plot beam envelope
plotRDT
plotWdispP plotWdispP Plot W functions
plot_betabeat function plot_betabeat(THERING_ref,THERING_mod)
plot_trajectory PLOT_TRAJECTORY Plots particle trajectories
ATtoG4BL function [outtext]=ATtoG4BL(P_0,particle,folder)
atfastring ATFASTRING Generate simplified AT structures
atsbreak ATSBREAK Insert markers at given s positions in a lattice
atsetRFCavity ATSETRFCAVITY - sets the RF Cavity with the passmethod RFCavityPass.
rmelem0 RMELEM0 removes elements of length 0 from the accelerator lattice
testdispersionfreesteering test errors and correction functions
atsetRFCavityErr ATSETRFCAVITY sets the RF Cavity with the passmethod RFCavityPass.
testsetRFCavityErr test errors and correction functions
testdispersioncorrection test errors and correction functions
testorbitbump test errors and correction functions
testorbitcorrection test errors and correction functions
BumpAtBPM4D function roff=BumpAtBPM(...
testorbitbump test matching orbit bump
testtrajectorycorrection test errors and correction functions
testerr
testcor
SetLargeErrorList SETLARGEERRORLIST Sets given error list
SetESRFAlgeAlignmentError function SetESRFAlgeAlignmentError(...
testerr
compRotCorVsDip
compRotCorVsDipQuad
testerr
testerrRotCorrector
ThetaPhiGirder rtp=ThetaPhiGirder(r,mag_gr)
setBpmOffsetOnDipoleRef % set bpm on curve defined by dipole misalignments
seterrorwave
atsurvey2spos returns closest lattics s coordinates to xycoord points
atreadbeta ATREADBETA reads a BETA file
SOURCE CODE
function spos = findspos(line,refpts)
%FINDSPOS returns longitudinal positions of accelerator lattice elements.
%  Return value is a row vector of positions S at the entrance of each
%  element specified REFPTS (index list or logical mask)
%
% Note: REFPTS is an array of increasing indexes that
%   select elements from range 1 to length(LATTICE)+1.
%   REFPTS is allowed to go 1 point beyond the
%   number of elements. In this case the last point is
%   the EXIT of the last element. If LATTICE is a RING
%   it is also the entrance of the first element after 1 turn.
%
%   Note:
%   1. Use findspos(RING,1:length(RING)) for to find
%      longitudinal position of all elements
%   2. Use findspos(LINE,length(LINE)+1) to find the
%      total physical length
%   3. If line is a closed ring, exit of the last element
%      is also the entrance to the first.
if isvector(line)
    L=[0;cumsum(cellfun(@(el) el.Length,line(:),'ErrorHandler',@(w,el) 0))];
else
    L=[0;cumsum(cellfun(@(el) el.Length,line(:,1),'ErrorHandler',@(w,el) 0))];
end
spos=L(refpts)';
end