Description of atgetfieldvalues
atgetfieldvalues
PURPOSE
ATGETFIELDVALUES retrieves the field values AT cell array of elements
SYNOPSIS
function values = atgetfieldvalues(ring,varargin)
DESCRIPTION
ATGETFIELDVALUES retrieves the field values AT cell array of elements
 VALUES = ATGETFIELDVALUES(RING,'field') extracts the values of
 the field 'field' in all the elements of RING
 VALUES = ATGETFIELDVALUES(RING,INDEX,'field') extracts the values of
 the field 'field' in the elements of RING selected by INDEX
 if RING{I}.FIELD is a numeric scalar
    VALUES is a length(INDEX) x 1 array
 otherwise
    VALUES is a length(INDEX) x 1 cell array
 More generally ATGETFIELDVALUES(RING,INDEX,subs1,subs2,...) will call
  GETFIELD(RING{I},subs1,subs2,...) for I in INDEX
 Examples:
 V=ATGETFIELDVALUES(RING,1:10,'PolynomB') is a 10x1  cell array
 such that V{I}=RING{I}.PolynomB for I=1:10
 V=ATGETFIELDVALUES(RING(1:10),'PolynomB',{1,2}) is a 10x1 array
 such that V(I)=RING{I},PolynomB(1,2)
 See also ATSETFIELDVALUES ATGETCELLS GETCELLSTRUCT FINDCELLS
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atcavityoff ATCAVITYOFF switches cavities off
atcavityon ATRADON switches RF cavities on
atRFacc ATRFACC Computes RF acceptance of the ring
atenergy ATENERGY Gets the lattice energy
atradoff ATRADOFF switches radiation and cavity off
atradon ATRADON switches RF and radiation on
atavedata ATAVEDATA Average of optical functions on selected elements
atplotsyn ATPLOTSYN Helper function for ATPLOT
atfastring ATFASTRING Generate simplified AT structures
atfitchrom ATFITTUNE fits chromaticites by scaling 2 sextupol families
atfittune ATFITTUNE fits linear tunes by scaling 2 quadrupole families
atreduce ATREDUCE Remove useless elements from an AT structure
atsplitelem ATSPLITELEM Creates a line by inserting one or more elements into a base element
getcellstruct GETCELLSTRUCT retrieves the field values MATLAB cell array of structures
atdispersionfreesteering function [...
EquivalentGradientsFromAlignments6D EQUIVALENTGRADIENTSFROMALIGNMENTS6D Estimated normal quad gradients from sext offsets
atQuadRDTdispersioncorrection ATQUADRDTDISPERSIONCORRECTION - Make dispersion correction based on RDTs
atRDTdispersioncorrection ATRDTDISPERSIONCORRECTION Makes dispersion correction based on RDTs
atRDTdispersionmeasuredcorrection ATRDTDISPERSIONMEASUREDCORRECTION Makes correction of dispersion based on
atSkewRDTdispersioncorrection function [...
atavedata_mod ATAVEDATA Average of optical functions on selected elements
atRFcorrection function [...
atsetRFCavityErr ATSETRFCAVITY sets the RF Cavity with the passmethod RFCavityPass.
CorrectionChain
atcorrectdispersion function [...
atcorrectorbit
BumpAtBPM function roff=BumpAtBPM(...
atset_s_shift ATSET_S_SHIFT Implements DS longitudinal position drift
ThetaPhiGirder rtp=ThetaPhiGirder(r,mag_gr)
UniformGirderErrors function ring=UniformGirderErrors(ring)
setFieldIntegralError function rerr=setFieldIntegralError(r0,rerr,indx,order,Nsigma,sigmaperc)
SUBFUNCTIONS
function values = atgetfield(line,varargin)
function [val,isnumscal,isok]=scan(el)
SOURCE CODE
function values = atgetfieldvalues(ring,varargin)
%ATGETFIELDVALUES retrieves the field values AT cell array of elements
%
% VALUES = ATGETFIELDVALUES(RING,'field') extracts the values of
% the field 'field' in all the elements of RING
%
% VALUES = ATGETFIELDVALUES(RING,INDEX,'field') extracts the values of
% the field 'field' in the elements of RING selected by INDEX
%
% if RING{I}.FIELD is a numeric scalar
%    VALUES is a length(INDEX) x 1 array
% otherwise
%    VALUES is a length(INDEX) x 1 cell array
%
%
% More generally ATGETFIELDVALUES(RING,INDEX,subs1,subs2,...) will call
%  GETFIELD(RING{I},subs1,subs2,...) for I in INDEX
%
% Examples:
%
% V=ATGETFIELDVALUES(RING,1:10,'PolynomB') is a 10x1  cell array
% such that V{I}=RING{I}.PolynomB for I=1:10
%
% V=ATGETFIELDVALUES(RING(1:10),'PolynomB',{1,2}) is a 10x1 array
% such that V(I)=RING{I},PolynomB(1,2)
%
%
% See also ATSETFIELDVALUES ATGETCELLS GETCELLSTRUCT FINDCELLS
if islogical(varargin{1}) || isnumeric(varargin{1})
    values=atgetfield(ring(varargin{1}),varargin{2:end});
else
    values=atgetfield(ring,varargin{:});
end
    function values = atgetfield(line,varargin)
        [values,isnumscal,isok]=cellfun(@scan,line(:),'UniformOutput',false);
        isok=cat(1,isok{:});
        if all(cat(1,isnumscal{isok}))
            values(~isok)={NaN};
            values=cat(1,values{:});
        end
        function [val,isnumscal,isok]=scan(el)
            try
                val=getfield(el,varargin{:});
                isnumscal=isnumeric(val) && isscalar(val);
                isok=true;
            catch
                val=[];
                isnumscal=false;
                isok=false;
            end
        end
    end
end