Description of atgetcells
atgetcells
PURPOSE
ATGETCELLS performs a search on MATLAB cell arrays of structures
SYNOPSIS
function ok=atgetcells(cellarray, field, varargin)
DESCRIPTION
ATGETCELLS performs a search on MATLAB cell arrays of structures
 OK = ATGETCELLS(RING, 'field')
   returns indexes of elements that have a field named 'field'
 OK = ATGETCELLS(RING, 'field', VALUE1...)
   returns indexes of elements whose field 'field'
   is equal to VALUE1, VALUE2, ... or VALUEN. Where VALUE can either be
   character strings or a number. If its a character string REGULAR
   expressions can be used.
 OK = ATGETCELLS(RING, 'field', @TESTFUNCTION, ARGS...)
   Uses the user-defined TESTFUNCTION to select array elements
   TESTFUNCTION must be of the form:
       OK=TESTFUNTION(ATELEM,FIELDVALUE,ARGS...)
 OK is a logical array with the same size as RING, refering to matching
 elements in RING
 See also ATGETFIELDVALUES, ATSETFIELDVALUES, FINDCELLS, REGEXPI
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atcavityoff ATCAVITYOFF switches cavities off
atcavityon ATRADON switches RF cavities on
atVariableBuilder atVarBuilder create a simple variable structure for use with atmatch
atRFacc ATRFACC Computes RF acceptance of the ring
findorbit6 FINDORBIT6 finds closed orbit in the full 6-d phase space
atenergy ATENERGY Gets the lattice energy
atradoff ATRADOFF switches radiation and cavity off
atradon ATRADON switches RF and radiation on
atavedata ATAVEDATA Average of optical functions on selected elements
atbaseplot ATBASEPLOT Plots data generated by a user-supplied function
ataddmpoleerrors ataddrandmpole adds a random multipole component to all elements of type
atfastring ATFASTRING Generate simplified AT structures
atfitchrom ATFITTUNE fits chromaticites by scaling 2 sextupol families
atfittune ATFITTUNE fits linear tunes by scaling 2 quadrupole families
atreduce ATREDUCE Remove useless elements from an AT structure
atsbreak ATSBREAK Insert markers at given s positions in a lattice
atsplitelem ATSPLITELEM Creates a line by inserting one or more elements into a base element
findcells FINDCELLS performs a search on MATLAB cell arrays of structures
atdispersionfreesteering function [...
testdispersionfreesteering test errors and correction functions
EquivalentGradientsFromAlignments6D EQUIVALENTGRADIENTSFROMALIGNMENTS6D Estimated normal quad gradients from sext offsets
atQuadRDTdispersioncorrection ATQUADRDTDISPERSIONCORRECTION - Make dispersion correction based on RDTs
atRDTdispersioncorrection ATRDTDISPERSIONCORRECTION Makes dispersion correction based on RDTs
atRDTdispersionmeasuredcorrection ATRDTDISPERSIONMEASUREDCORRECTION Makes correction of dispersion based on
atSkewRDTdispersioncorrection function [...
atavedata_mod ATAVEDATA Average of optical functions on selected elements
testRDTdispersionfreesteering test errors and correction functions
atRFcorrection function [...
testsetRFCavityErr test errors and correction functions
CorrectionChain
DisplayCorrectionEffect [d0,de,dc]=DisplayCorrectionEffect(...
testcorrectionchain test errors and correction functions
atcorrectdispersion function [...
testdispersioncorrection test errors and correction functions
atcorrectorbit
testorbitcorrection test errors and correction functions
testorbitbump test matching orbit bump
getresponsematrices
atfirstturntrajectory ATFIRSTTURNTRAJECTORY Makes first turn correction
testorbitaftertrajectory test errors and correction functions
testtrajectorycorrection test errors and correction functions
testfittunedelta2fam test errors and correction functions
testerr
testerr
testerr
testerr
testerr
testerr
SetLargeErrorList SETLARGEERRORLIST Sets given error list
SetESRFAlgeAlignmentError function SetESRFAlgeAlignmentError(...
testerr
compRotCorVsDipQuad
testerr
getMagGroupsFromGirderIndex GETMAGGROUPSFROMGIRDERINDEX Gets magnets on a girder
atreadbeta ATREADBETA reads a BETA file
SUBFUNCTIONS
function ok=defaultfunc(el,fieldval,varargin)
SOURCE CODE
function ok=atgetcells(cellarray, field, varargin)
%ATGETCELLS performs a search on MATLAB cell arrays of structures
%
% OK = ATGETCELLS(RING, 'field')
%   returns indexes of elements that have a field named 'field'
%
% OK = ATGETCELLS(RING, 'field', VALUE1...)
%   returns indexes of elements whose field 'field'
%   is equal to VALUE1, VALUE2, ... or VALUEN. Where VALUE can either be
%   character strings or a number. If its a character string REGULAR
%   expressions can be used.
%
% OK = ATGETCELLS(RING, 'field', @TESTFUNCTION, ARGS...)
%   Uses the user-defined TESTFUNCTION to select array elements
%   TESTFUNCTION must be of the form:
%       OK=TESTFUNTION(ATELEM,FIELDVALUE,ARGS...)
%
% OK is a logical array with the same size as RING, refering to matching
% elements in RING
%
% See also ATGETFIELDVALUES, ATSETFIELDVALUES, FINDCELLS, REGEXPI
% Check if the first argument is the cell array of structures
if ~iscell(cellarray)
    error('The first argument must be a cell array of structures')
end
% Check if the second argument is a string
if(~ischar(field))
    error('The second argument must be a character string')
end
if nargin<3
    tesfunc=@(elem,field) true;
    vals={};
elseif isa(varargin{1},'function_handle')
    tesfunc=varargin{1};
    vals=varargin(2:end);
else
    tesfunc=@defaultfunc;
    vals=varargin;
end
ok=cellfun(@(elem) isfield(elem,field) && tesfunc(elem,elem.(field),vals{:}), cellarray);
    function ok=defaultfunc(el,fieldval,varargin) %#ok<INUSL>
        ok=false;
        if ischar(fieldval)
            %ok=any(cellfun(@charcompare,varargin))
            for j=1:length(varargin)
                if ischar(varargin{j}) && ~isempty(regexpi(fieldval,['^' varargin{j} '$']))
                    ok=true;
                    break;
                end
            end
        elseif isnumeric(fieldval)
            %ok=any(cellfun(@numcompare,varargin))
            for j=1:length(varargin)
                if isnumeric(varargin{j}) && fieldval==varargin{j}
                    ok=true;
                    break;
                end
            end
        end
%         function ok=charcompare(val)
%             ok=ischar(val) && ~isempty(regexpi(fieldval,['^' val '$']));
%         end
%         function ok=numcompare(val)
%             ok=isnumeric(val) && fieldval==val;
%         end
    end
end