Description of buildlat
buildlat
PURPOSE
BUILDLAT places elements from FAMLIST into cell array THERING
SYNOPSIS
function buildlat(ELIST)
DESCRIPTION
BUILDLAT places elements from FAMLIST into cell array THERING
 in the order given by ineger arry ELIST
 to be use in Accelerator Toolbox lattice definition files
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sp3v81f All the dipole and quadrupole lengths are effective lengths
spear2 SPEAR2 example lattice definition file
spear2resp SPEAR2RESP example SPEAR2 lattice with orbit correctors and BPMS
SOURCE CODE
function buildlat(ELIST)
%BUILDLAT places elements from FAMLIST into cell array THERING
% in the order given by ineger arry ELIST
% to be use in Accelerator Toolbox lattice definition files
global FAMLIST THERING
THERING=cell(size(ELIST(:)));
for i=1:length(THERING)
   THERING{i} = FAMLIST{ELIST(i)}.ElemData;
   FAMLIST{ELIST(i)}.NumKids=FAMLIST{ELIST(i)}.NumKids+1;
   FAMLIST{ELIST(i)}.KidsList = [FAMLIST{ELIST(i)}.KidsList i];
end
GitHub Website at © 2018