Description of exitfields
exitfields
PURPOSE
EXITFIELDS() Return the list of field names affecting the element exit
SYNOPSIS
function fnames = exitfields(varargin)
DESCRIPTION
EXITFIELDS() Return the list of field names affecting the element exit
 Optional arguments:
 'KeepAxis', if present, rotations translations are excluded from list
see also: entrancefields atdivelem
CROSS-REFERENCE INFORMATION
This function calls:
getflag GETFLAG Check the presence of a flag in an argument list
This function is called by:
atdivelem LINE=ATDIVELEM(ELEM,FRAC) divide an element into pieces
atreduce ATREDUCE Remove useless elements from an AT structure
SOURCE CODE
function fnames = exitfields(varargin)
%EXITFIELDS() Return the list of field names affecting the element exit
%
% Optional arguments:
% 'KeepAxis', if present, rotations translations are excluded from list
%
%see also: entrancefields atdivelem
rottrasl=getflag(varargin,'KeepAxis');
start=1;
if rottrasl
   start=3; % remove R1 T1 from list of field at entrance
end
persistent fnms
if isempty(fnms)
    fnms={'T2','R2','ExitAngle','FringeInt2',...
        'FringeBendExit','FringeQuadExit'};
end
fnames=fnms(start:end);
end
GitHub Website at © 2018