Description of findcells
findcells
PURPOSE
FINDCELLS performs a search on MATLAB cell arrays of structures
SYNOPSIS
function index = findcells(CELLARRAY, field, varargin)
DESCRIPTION
FINDCELLS performs a search on MATLAB cell arrays of structures
 INDEX = FINDCELLS(CELLARRAY, 'field')
   returns indexes of elements that have a field named 'field'
 INDEX = FINDCELLS(CELLARRAY, 'field', VALUE)
   returns indexes of elements whose field 'field'
   is equal to VALUE1, VALUE2, ... or VALUEN. Where VALUE can either be
   character strings or a number. If its a character string REGULAR
   expressions can be used.
 Example:
   findcells(THERING,'Length',0, 0.2);  % will match elements of
                                          lengths 0 and 0.2
   findcells(THERING,'FamName','SFA','SDA');
 See also ATGETCELLS, GETCELLSTRUCT, SETCELLSTRUCT, REGEXPI
CROSS-REFERENCE INFORMATION
This function calls:
atgetcells ATGETCELLS performs a search on MATLAB cell arrays of structures
This function is called by:
add_ID add_ID adds IDelem at the beginning and subtracts the length from
VaryQuadFam
runtotest_atmatch macro match dba test lattice beta functions and dispersion using
run_BumpFit fit a bump using correctors
demoknob DEMOKNOB illustrates the use of MATLAB GUI controls with AT
linoptdemo LINOPTDEMO script illustrates the use of LINOPT
ohmienvelopedemo OHMIENVELOPEDEMO illustrates the use of OHMIENVELOPE function
findrespmdemo FINDRESPMDEMO response matrix demo
makeFastRingWithBBR SI units
intelem INTELEM Interactive element editor.
atsetcavity ATSECAVITY Sets the synchronous phase of the cavity assuming radiation
cavityoff CAVITYOFF turns cavities OFF
cavityon CAVITYON turns Cavities ON
computeRDT COMPUTERDT Computes Hamiltonian resonance driving terms (RDTs)
atsummary ATSUMMARY - Prints out the paramters of the current AT lattice
ringpara RINGPARA Calculates various ring parameters
radiationoff RADIATIONOFF turns classical radiation OFF
radiationon RADIATIONON turns classical radiation ON
TouschekPiwinskiLifeTime function [Tl,contributionsTL]=TouschekPiwinskiLifeTime(r,dpp,Ib)
simpletestToucheckLT simple example of use of toucheck lifetime formula:
fitchrom2 FITCHROM2 fits chromaticity of THERING using 2 sextupole families
fittune2 FITTUNE2 fits linear tunes of THERING using 2 quadrupole families
plCorrectorStrength DEFAULTPLOT Default plotting function for ATPLOT
plEmitContrib plots H/rho³ at every dipole
plPolynomBComp PLPOLYNOMBCOMP PlotBn coefficient with normalization
plPolynomBSxtOct PLPOLYNOMBSXTOCT Plots Bn for sextupole and octupole magnets
plotB0curlyh
plotRDT
ATtoG4BL function [outtext]=ATtoG4BL(P_0,particle,folder)
atparamgroup PARAMETER GROUP in AT is a general way
mkparamgroup MKPARAMGROUP simplifies creation of AT parameter groups
atmakefielderrstruct MAKERNDFIELDERRS will create a field error data structure
atsetRFCavity ATSETRFCAVITY - sets the RF Cavity with the passmethod RFCavityPass.
combinebypassmethod COMBINEBYPASSMETHOD combines adjacent elements that have the same specified pass method
combinelinear45 COMBINELINEAR45 combines adjacent elements that use 4-by-5 PassMethods
findtags FINDTAGS looks for string matches in 'Tag' field of AT lattice elements
settags SETTAGS sets the 'Tag' field in AT lattice elements
plotAperture PLOTAPERTURE Plots x and y aperture.
plotERAperture PLOTERAPERTURE Plots RApertures EApertures aperture.
plotRAperture PLOTRAPERTURE Plots Rectangular aperture
atsetRFCavityErr ATSETRFCAVITY sets the RF Cavity with the passmethod RFCavityPass.
BumpAtBPM4D function roff=BumpAtBPM(...
fittunedelta2fam rerr=fittunedelta2fam(rerr,r0)
testerr
testcor
SetLargeErrorList SETLARGEERRORLIST Sets given error list
atset_s_shift ATSET_S_SHIFT Implements DS longitudinal position drift
GetMisalignments this function retrives 3 vectors, for x and y misalignments and tilts
GetExistingErrors this function retrives 6 vectors, for x, y,s misalignments,
UniformGirderErrors function ring=UniformGirderErrors(ring)
getMagGroupsFromMagNum GETMAGGROUPSFROMMAGNUM - Gets magnet from a Magnet group
setBpmOffsetOnDipoleRef % set bpm on curve defined by dipole misalignments
calc_Touschek tauT = calc_Touschek(THERING, Ib)
calc_dppAperture calculate the momentum aperture at each location of the ring due to
scalesext newring=scalesext(ring,sextfam,scale)
setsext newring=setsext(ring,fam,val);
SOURCE CODE
function index = findcells(CELLARRAY, field, varargin)
%FINDCELLS performs a search on MATLAB cell arrays of structures
%
% INDEX = FINDCELLS(CELLARRAY, 'field')
%   returns indexes of elements that have a field named 'field'
%
% INDEX = FINDCELLS(CELLARRAY, 'field', VALUE)
%   returns indexes of elements whose field 'field'
%   is equal to VALUE1, VALUE2, ... or VALUEN. Where VALUE can either be
%   character strings or a number. If its a character string REGULAR
%   expressions can be used.
%
% Example:
%   findcells(THERING,'Length',0, 0.2);  % will match elements of
%                                          lengths 0 and 0.2
%   findcells(THERING,'FamName','SFA','SDA');
%
% See also ATGETCELLS, GETCELLSTRUCT, SETCELLSTRUCT, REGEXPI
index=reshape(find(atgetcells(CELLARRAY,field,varargin{:})),1,[]);
GitHub Website at © 2018