Description of getcellstruct
getcellstruct
PURPOSE
GETCELLSTRUCT retrieves the field values MATLAB cell array of structures
SYNOPSIS
function values = getcellstruct(CELLARRAY,field,index,varargin)
DESCRIPTION
GETCELLSTRUCT retrieves the field values MATLAB cell array of structures
 VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX,M,N)
 VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX,M) can be used
   for one dimensional vectors
 VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX) is the same as
   GETCELLSTRUCT(CELLARRAY,'field',index,1,1) if the field data
   is a scalar
 VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX) is a MATLAB cell array
      of strings if specified fields contain strings.
 See also ATGETFIELDVALUES SETCELLSTRUCT FINDCELLS
CROSS-REFERENCE INFORMATION
This function calls:
atgetfieldvalues ATGETFIELDVALUES retrieves the field values AT cell array of elements
This function is called by:
runtotest_atmatch macro match dba test lattice beta functions and dispersion using
intlat INTLAT Interactive AT lattice editor
computeRDT COMPUTERDT Computes Hamiltonian resonance driving terms (RDTs)
ringpara RINGPARA Calculates various ring parameters
TouschekPiwinskiLifeTime function [Tl,contributionsTL]=TouschekPiwinskiLifeTime(r,dpp,Ib)
simpletestToucheckLT simple example of use of toucheck lifetime formula:
fitchrom2 FITCHROM2 fits chromaticity of THERING using 2 sextupole families
fittune2 FITTUNE2 fits linear tunes of THERING using 2 quadrupole families
plCorrectorStrength DEFAULTPLOT Default plotting function for ATPLOT
plEmitContrib plots H/rho³ at every dipole
plPolynomBComp PLPOLYNOMBCOMP PlotBn coefficient with normalization
plPolynomBSxtOct PLPOLYNOMBSXTOCT Plots Bn for sextupole and octupole magnets
plotB0curlyh
AT_2_Elegant this functions converts the AT lattice AT_ring in elegant form.
AT_2_mad8 function [elelat,def,lines]=AT_2_mad8(AT_ring,linename)
AT_2_madX function [elelat,defs,lines]=AT_2_madX(AT_ring,linename)
AT_2_OPA function AT_2_OPA(AT_ring,linename)
plotAperture PLOTAPERTURE Plots x and y aperture.
plotERAperture PLOTERAPERTURE Plots RApertures EApertures aperture.
plotRAperture PLOTRAPERTURE Plots Rectangular aperture
DisplayCorrectionEffect [d0,de,dc]=DisplayCorrectionEffect(...
atfirstturntrajectory ATFIRSTTURNTRAJECTORY Makes first turn correction
AssignFieldErr function r=AssignFieldErr(r,refpos,N,rho,BNn,ANn)
GetMisalignments this function retrives 3 vectors, for x and y misalignments and tilts
GetExistingErrors this function retrives 6 vectors, for x, y,s misalignments,
getMagGroupsFromMagNum GETMAGGROUPSFROMMAGNUM - Gets magnet from a Magnet group
calc_dppAperture calculate the momentum aperture at each location of the ring due to
SOURCE CODE
function values = getcellstruct(CELLARRAY,field,index,varargin)
%GETCELLSTRUCT retrieves the field values MATLAB cell array of structures
%
% VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX,M,N)
%
% VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX,M) can be used
%   for one dimensional vectors
%
% VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX) is the same as
%   GETCELLSTRUCT(CELLARRAY,'field',index,1,1) if the field data
%   is a scalar
%
% VALUES = GETCELLSTRUCT(CELLARRAY,'field',INDEX) is a MATLAB cell array
%      of strings if specified fields contain strings.
%
% See also ATGETFIELDVALUES SETCELLSTRUCT FINDCELLS
values=atgetfieldvalues(CELLARRAY(index),field,varargin);
end
GitHub Website at © 2018