Description of getoption
getoption
PURPOSE
GETOPTION Extract a keyword argument from the input arguments
SYNOPSIS
function [optval,opts] = getoption(opts,optname,defval)
DESCRIPTION
GETOPTION Extract a keyword argument from the input arguments
OPTVAL=GETOPTION(ARGS,OPTNAME)
   Extract a keyword argument, in the form of a pair "name,value" from
   input arguments (typically from VARARGIN).
    Return the value of the desired option from the argument list and
    send an exception if it is absent. Option names are case insensitive
 ARGS:     Argument list (cell array or structure)
 OPTNAME:    Name of the desired option
OPTVAL=GETOPTION(ARGS,OPTNAME,OPTDEFAULT)
    Return a default value if the option is absent
 OPTDEFAULT:   Default value for the option
[OPTVAL,NEWARGS]=GETOPTION(...)
  Return the remaining arguments after removing the processed ones
Example:
function testfunc(varargin)
[optflag,args]=getflag(varargin,'option');     % Extract an optional flag
[range,args]=getoption(args,'Range', 1:10);    % Extract a keyword argument
[width, height]=getargs(args,{210,297});       % Extract positional arguments
See also GETFLAG, GETARGS
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atnuampl ATNUAMPL computes tune shift with amplitude
atbaseplot ATBASEPLOT Plots data generated by a user-supplied function
atplot ATPLOT Plots optical functions
linepass LINEPASS tracks particles through each element of the cell array LINE
ringpass RINGPASS tracks particles through each element of the cell array RING
atM66 ATM66(FAMNAME,M66,PASSMETHOD)
atM66Tijk ATM66(FAMNAME,M66,Tijk,PASSMETHOD)
atQuantDiff atQuantDiff creates a quantum diffusion element
ataperture ATAPERTURE Creates a aperture element
atbaselem ATBASELEM Create an AT element structure + various checks
atcorrector ATCORRECTOR Creates a drift space element with class 'Corrector'
atdrift ATDRIFT Creates a drift space element with Class 'Drift'
atmarker ATMARKER Creates a marker space element
atmonitor ATMONITOR Creates a Beam Position Monitor element with Class 'Monitor'
atmultipole ATMULTIPOLE Creates a multipole element
atquadrupole ATQUADRUPOLE Creates a quadrupole element with Class 'Quadrupole'
atrbend ATRBEND Creates a rectangular bending magnet element with class 'Bend'
atrfcavity ATRFCAVITY Creates an rfcavity element with Class 'RFCavity'
atringparam ATRINGPARAM Creates a RingParameter Element which should go at the beginning of the ring
atsbend ATSBEND Creates a sector bending magnet element with class 'Bend'
atsextupole ATSEXTUPOLE Creates a sextupole element with class 'Sextupole'
atskewquad ATSKEWQUAD Creates a skew quadrupole element with Class 'Multipole'
atsolenoid ATSOLENOID Creates a new solenoid element with Class 'Solenoid'
atthinmultipole ATTHINMULTIPOLE Creates a thin multipole element
atgeometry ATGEOMETRY Computes the 2-D position of all elements (no vertical bend)
atgeometry3 ATGEOMETRY3 Computes the 3-D position of all elements
SOURCE CODE
function [optval,opts] = getoption(opts,optname,defval)
%GETOPTION Extract a keyword argument from the input arguments
%
%OPTVAL=GETOPTION(ARGS,OPTNAME)
%   Extract a keyword argument, in the form of a pair "name,value" from
%   input arguments (typically from VARARGIN).
%    Return the value of the desired option from the argument list and
%    send an exception if it is absent. Option names are case insensitive
% ARGS:     Argument list (cell array or structure)
% OPTNAME:    Name of the desired option
%
%
%OPTVAL=GETOPTION(ARGS,OPTNAME,OPTDEFAULT)
%    Return a default value if the option is absent
% OPTDEFAULT:   Default value for the option
%
%[OPTVAL,NEWARGS]=GETOPTION(...)
%  Return the remaining arguments after removing the processed ones
%
%Example:
%
%function testfunc(varargin)
%
%[optflag,args]=getflag(varargin,'option');     % Extract an optional flag
%[range,args]=getoption(args,'Range', 1:10);    % Extract a keyword argument
%[width, height]=getargs(args,{210,297});       % Extract positional arguments
%
%See also GETFLAG, GETARGS
if iscell(opts)
    ok=[strcmpi(optname,opts(1:end-1)) false];  %option name cannot be the last argument
    if any(ok)
        okval=circshift(ok,[0,1]);
        defval=opts{find(okval,1,'last')};
        opts(ok|okval)=[];
    end
elseif isstruct(opts)
    if isfield(opts,optname)
        defval=opts.(optname);
        opts=rmfield(opts,optname);
    end
end
try
    optval=defval;
catch       % Dould be 'MATLAB:minrhs'
    error('getoption:missing','Option "%s" is missing',optname);
end
end
GitHub Website at © 2018