Description of parseargs
parseargs
PURPOSE
PARSEARGS Check and expands optional argument lists
SYNOPSIS
function varargout = parseargs(default_values,args)
DESCRIPTION
PARSEARGS Check and expands optional argument lists
ARGOUT=PARSEARGS(DEFAULT_VALUES,ARGIN)
[ARG1,ARG2,...]=PARSEARGS(DEFAULT_VALUES,ARSIN)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
atcavityoff ATCAVITYOFF switches cavities off
atcavityon ATRADON switches RF cavities on
atx ATX Computes and displays global information
atradoff ATRADOFF switches radiation and cavity off
atradon ATRADON switches RF and radiation on
linepass LINEPASS tracks particles through each element of the cell array LINE
ringpass RINGPASS tracks particles through each element of the cell array RING
decodeatargs DECODEATARGS separates arguments and resources
atgeometry ATGEOMETRY Computes the 2-D position of all elements (no vertical bend)
atgeometry3 ATGEOMETRY3 Computes the 3-D position of all elements
SOURCE CODE
function varargout = parseargs(default_values,args)
%PARSEARGS Check and expands optional argument lists
%ARGOUT=PARSEARGS(DEFAULT_VALUES,ARGIN)
%[ARG1,ARG2,...]=PARSEARGS(DEFAULT_VALUES,ARSIN)
na=min(length(default_values),length(args));
ok=~cellfun(@(arg) isempty(arg)&&isnumeric(arg),args(1:na));
default_values(ok)=args(ok);
if nargout==length(default_values)
    varargout=default_values;
else
    varargout{1}=default_values;
end
end