Description of reverse
reverse
PURPOSE
REVERSE reverses the order of elements in a one-dimensional MATLAB ARRAY
SYNOPSIS
function z = reverse(A)
DESCRIPTION
REVERSE reverses the order of elements in a one-dimensional MATLAB ARRAY
 ARRAY2 = REVERSE(ARRAY1)
   ARRAY1 can be numeric, char (string), or cell array
CROSS-REFERENCE INFORMATION
This function calls:
reverse REVERSE reverses the order of elements in a one-dimensional MATLAB ARRAY
This function is called by:
reverse REVERSE reverses the order of elements in a one-dimensional MATLAB ARRAY
splitdrift SPLITDRIFT inserts an element into a drift space
sp3v81f All the dipole and quadrupole lengths are effective lengths
spear2 SPEAR2 example lattice definition file
spear2rad SPEAR2RAD example lattice definition file with CAVITY and CLASSICAL radiation
spear2resp SPEAR2RESP example SPEAR2 lattice with orbit correctors and BPMS
spear3 SPEAR3 Load the SPEAR3 lattice structure
SOURCE CODE
function z = reverse(A)
%REVERSE reverses the order of elements in a one-dimensional MATLAB ARRAY
%
% ARRAY2 = REVERSE(ARRAY1)
%   ARRAY1 can be numeric, char (string), or cell array
L = length(A);
if iscell(A)
   z = cell(size(A));
   for i=1:L
      z{i} = A{L-i+1};
   end
elseif isnumeric(A)
   z = zeros(size(A));
   for i=1:L
      z(i) = A(L-i+1);
   end
elseif ischar(A)
    z = char(reverse(double(A)));
end