Description of mux
mux
PURPOSE
SYNOPSIS
function m=mux(lindata)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
runtotest_atmatch macro match dba test lattice beta functions and dispersion using
twissline TWISSLINE calculates linear optics functions for an UNCOUPLED transport line
atmatchtunedelta function arcchrom0=atmatchtunedelta(arc,c,quadfams)
SOURCE CODE
function m=mux(lindata)
m=lindata(end).mu(1)/2/pi;
GitHub Website at © 2018