Description of VaryQuadFam
VaryQuadFam
PURPOSE
SYNOPSIS
function R=VaryQuadFam(R,K1val,fam)
DESCRIPTION
 functions returns a new ring with a different value for K1 of fam
CROSS-REFERENCE INFORMATION
This function calls:
findcells FINDCELLS performs a search on MATLAB cell arrays of structures
setcellstruct SETCELLSTRUCT sets the field values of MATLAB cell array of structures
This function is called by:
runtotest_atmatch macro match dba test lattice beta functions and dispersion using
SOURCE CODE
function R=VaryQuadFam(R,K1val,fam)
%
% functions returns a new ring with a different value for K1 of fam
indfam=findcells(R,'FamName',fam);
%*ones(size(indfam))
R=setcellstruct(R,'PolynomB',indfam,K1val*ones(size(indfam)),1,2);