Description of plot_trajectory
plot_trajectory
PURPOSE
PLOT_TRAJECTORY Plots particle trajectories
SYNOPSIS
function varargout=plot_trajectory(varargin)
DESCRIPTION
PLOT_TRAJECTORY    Plots particle trajectories
Helper function for atplot: plot
- H and V trajectories on the left axis
PLOTDATA=PLOT_TRAJECTORY(LINDATA,RING,DPP,IN)
[S,PLOTDATA]=PLOT_TRAJECTORY(RING,DPP,IN)
CROSS-REFERENCE INFORMATION
This function calls:
findspos FINDSPOS returns longitudinal positions of accelerator lattice elements.
atreforbit ATREFORBIT Computes the coordinates of the local referential
plot_trajectory PLOT_TRAJECTORY Plots particle trajectories
linepass LINEPASS tracks particles through each element of the cell array LINE
This function is called by:
plot_trajectory PLOT_TRAJECTORY Plots particle trajectories
SOURCE CODE
function varargout=plot_trajectory(varargin)
%PLOT_TRAJECTORY    Plots particle trajectories
%
%Helper function for atplot: plot
%- H and V trajectories on the left axis
%
%PLOTDATA=PLOT_TRAJECTORY(LINDATA,RING,DPP,IN)
%
%[S,PLOTDATA]=PLOT_TRAJECTORY(RING,DPP,IN)
if nargout == 1     % From atplot
    nparts=size(varargin{4},2);
    refpts=1:length(varargin{2})+1;
    rout=linepass(varargin{[2 4]},refpts);
    [xref,zref]=atreforbit(varargin{2});
    xx=reshape(rout(1,:),nparts,[])'+xref(:,ones(1,nparts));
    yy=reshape(rout(3,:),nparts,[])'+zref(:,ones(1,nparts));
    labs=[arrayfun(@(n) num2str(n,'x%d'),1:nparts,'UniformOutput',false),...
        arrayfun(@(n) num2str(n,'z%d'),1:nparts,'UniformOutput',false)];
    plotdata(1).values=[xx yy];
    plotdata(1).labels=labs;
    plotdata(1).axislabel='x,z [m]';
    varargout={plotdata};
else                % From atbaseplot
    s=findspos(varargin{1},1:length(varargin{1})+1);
    varargout={s,plot_trajectory([],varargin{:})};
end
end