Description of FODO
FODO
PURPOSE
SYNOPSIS
function ring=FODO()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
atsetcavity ATSECAVITY Sets the synchronous phase of the cavity assuming radiation
atdrift ATDRIFT Creates a drift space element with Class 'Drift'
atquadrupole ATQUADRUPOLE Creates a quadrupole element with Class 'Quadrupole'
atrfcavity ATRFCAVITY Creates an rfcavity element with Class 'RFCavity'
atsbend ATSBEND Creates a sector bending magnet element with class 'Bend'
atsextupole ATSEXTUPOLE Creates a sextupole element with class 'Sextupole'
This function is called by:
generateTrackData give some initial coordinates. Track through sample lattices.
testTracking test results of tracking against values previously computed
SOURCE CODE
function ring=FODO()
QF=atquadrupole('QF',0.5,1.2,'PassMethod','QuadMPoleFringePass','Energy',3e9);
QD=atquadrupole('QD',0.5,-1.2,'PassMethod','QuadMPoleFringePass','Energy',3e9);
Bend=atsbend('Bend',1,2*pi/40,'PassMethod','BndMPoleSymplectic4Pass','Energy',3e9);
RFC=atrfcavity('RFCav');
Dr=atdrift('Dr',0.5);
HalfDr=atdrift('Dr',0.25);
% p1Dr=atdrift('Dr',0.1);
p2Dr=atdrift('Dr',0.2);
% p3Dr=atdrift('Dr',0.3);
SF=atsextupole('SF',0.1,1);
SD=atsextupole('SD',0.1,-1);
cell=[{HalfDr};{Bend};{p2Dr};{SF};{p2Dr};{QF};{Dr};{Bend};{p2Dr};{SD};{p2Dr};{QD};{HalfDr}];
ring=repmat(cell,20,1);
ring=[{RFC};ring];
ring=atsetcavity(ring,5e5,0,100);
end
GitHub Website at © 2018