Description of drift
drift
PURPOSE
DRIFT Creates a drift element in old a AT version (Obsolete)
SYNOPSIS
function z = drift(fname,L,method)
DESCRIPTION
DRIFT Creates a drift element in old a AT version (Obsolete)
DRIFT('FAMILYNAME',Length [m],'METHOD')
    creates a new family in the FAMLIST - a structure with fields
        FamName            family name
        Length            length[m]
        PassMethod        name of the function on disk to use for tracking
 returns assigned address in the FAMLIST that is uniquely identifies
 the family
  NOTES
  1. Obsolete: use atdrift instead
  See also atdrift, atquadrupole, atsextupole, atsbend, atskewquad,
          atmultipole, atthinmultipole, atmarker, atcorrector
CROSS-REFERENCE INFORMATION
This function calls:
atdrift ATDRIFT Creates a drift space element with Class 'Drift'
This function is called by:
sp3v81f All the dipole and quadrupole lengths are effective lengths
spear2 SPEAR2 example lattice definition file
spear2rad SPEAR2RAD example lattice definition file with CAVITY and CLASSICAL radiation
spear2resp SPEAR2RESP example SPEAR2 lattice with orbit correctors and BPMS
SOURCE CODE
function z = drift(fname,L,method)
%DRIFT Creates a drift element in old a AT version (Obsolete)
%DRIFT('FAMILYNAME',Length [m],'METHOD')
%    creates a new family in the FAMLIST - a structure with fields
%        FamName            family name
%        Length            length[m]
%        PassMethod        name of the function on disk to use for tracking
% returns assigned address in the FAMLIST that is uniquely identifies
% the family
%
%  NOTES
%  1. Obsolete: use atdrift instead
%
%  See also atdrift, atquadrupole, atsextupole, atsbend, atskewquad,
%          atmultipole, atthinmultipole, atmarker, atcorrector
ElemData = atdrift(fname,L,method);
global FAMLIST
z = length(FAMLIST)+1; % number of declare families including this one
FAMLIST{z}.FamName = fname;
FAMLIST{z}.NumKids = 0;
FAMLIST{z}.KidsList= [];
FAMLIST{z}.ElemData= ElemData;
GitHub Website at © 2018