Description of rfcavity
rfcavity
PURPOSE
RFCAVITY Creates a RF cavity in older AT version
SYNOPSIS
function z = rfcavity(fname,L,V,F,H,method)
DESCRIPTION
RFCAVITY Creates a RF cavity in older AT version
RFCAVITY('FAMILYNAME',Length [m],Voltage[V], Frequency[Hz], Harmonic Number,'METHOD')
    creates a new family in the FAMLIST - a structure with fields
        FamName            family name
        Length            length[m]
        Voltage            peak voltage (V)
        Frequency        RF frequency [Hz]
         HarmNumber        Harmonic Number
        PassMethod        name of the function on disk to use for tracking
 returns assigned address in the FAMLIST that uniquely identifies
 the family
CROSS-REFERENCE INFORMATION
This function calls:
atrfcavity ATRFCAVITY Creates an rfcavity element with Class 'RFCavity'
This function is called by:
sp3v81f All the dipole and quadrupole lengths are effective lengths
spear2rad SPEAR2RAD example lattice definition file with CAVITY and CLASSICAL radiation
SOURCE CODE
function z = rfcavity(fname,L,V,F,H,method)
%RFCAVITY Creates a RF cavity in older AT version
%RFCAVITY('FAMILYNAME',Length [m],Voltage[V], Frequency[Hz], Harmonic Number,'METHOD')
%    creates a new family in the FAMLIST - a structure with fields
%        FamName            family name
%        Length            length[m]
%        Voltage            peak voltage (V)
%        Frequency        RF frequency [Hz]
%         HarmNumber        Harmonic Number
%        PassMethod        name of the function on disk to use for tracking
% returns assigned address in the FAMLIST that uniquely identifies
% the family
ElemData = atrfcavity(fname,L,V,F,H,[],method);
global FAMLIST
z = length(FAMLIST)+1; % number of declare families including this one
FAMLIST{z}.FamName = fname;
FAMLIST{z}.NumKids = 0;
FAMLIST{z}.KidsList= [];
FAMLIST{z}.ElemData= ElemData;