Description of atRFacc
atRFacc
PURPOSE
ATRFACC Computes RF acceptance of the ring
SYNOPSIS
function delta_max_rf = atRFacc(ring)
DESCRIPTION
ATRFACC Computes RF acceptance of the ring
 delta_max_rf = atRFacc(ring)
   The functions computes the RF acceptance of the ring
   ring is tha at lattice without radiation
   delta_max_rf is the RF acceptance
  See also RFacc
CROSS-REFERENCE INFORMATION
This function calls:
RFacc RFACC Computes the RF acceptance with linear formula
mcf MCF momentum compaction factor
atenergy ATENERGY Gets the lattice energy
atgetU0 ATGETU0 Computes Energy loss per turn in eV .
atgetcells ATGETCELLS performs a search on MATLAB cell arrays of structures
atgetfieldvalues ATGETFIELDVALUES retrieves the field values AT cell array of elements
This function is called by:
SOURCE CODE
function delta_max_rf = atRFacc(ring)
%ATRFACC Computes RF acceptance of the ring
% delta_max_rf = atRFacc(ring)
%   The functions computes the RF acceptance of the ring
%   ring is tha at lattice without radiation
%   delta_max_rf is the RF acceptance
%
%  See also RFacc
U0=atgetU0(ring);
E0=atenergy(ring);
alpha=mcf(ring,0);
maskcav=atgetcells(ring,'Class','RFCavity');
Voltage=atgetfieldvalues(ring,maskcav,'Voltage');
hnum=atgetfieldvalues(ring,maskcav,'HarmNumber');
h=hnum(1);
Vrf=sum(Voltage);
delta_max_rf=RFacc(Vrf,U0,E0,h,alpha);