Description of mcf
mcf
PURPOSE
MCF momentum compaction factor
SYNOPSIS
function a = mcf(RING,dp0)
DESCRIPTION
MCF momentum compaction factor
 MCF(RING) calculates momentum compaction factor of RING
 MCF(RING,DPP) computes the momentum compaction for off-momentum DPP
CROSS-REFERENCE INFORMATION
This function calls:
findorbit4 FINDORBIT4 finds closed orbit in the 4-d transverse phase
findspos FINDSPOS returns longitudinal positions of accelerator lattice elements.
ringpass RINGPASS tracks particles through each element of the cell array RING
This function is called by:
atRFacc ATRFACC Computes RF acceptance of the ring
atsummary ATSUMMARY - Prints out the paramters of the current AT lattice
atx ATX Computes and displays global information
atdispersionfreesteering function [...
testdispersionfreesteering test errors and correction functions
atQuadRDTdispersioncorrection ATQUADRDTDISPERSIONCORRECTION - Make dispersion correction based on RDTs
atRDTdispersioncorrection ATRDTDISPERSIONCORRECTION Makes dispersion correction based on RDTs
atRDTdispersionmeasuredcorrection ATRDTDISPERSIONMEASUREDCORRECTION Makes correction of dispersion based on
atSkewRDTdispersioncorrection function [...
atRFcorrection function [...
atsetRFCavityErr ATSETRFCAVITY sets the RF Cavity with the passmethod RFCavityPass.
DisplayCorrectionEffect [d0,de,dc]=DisplayCorrectionEffect(...
atcorrectdispersion function [...
testdispersioncorrection test errors and correction functions
atcorrectorbit
getresponsematrices
SOURCE CODE
function a = mcf(RING,dp0)
%MCF momentum compaction factor
% MCF(RING) calculates momentum compaction factor of RING
%
% MCF(RING,DPP) computes the momentum compaction for off-momentum DPP
if nargin < 2, dp0=0; end
ddp = 0.000001;
fp0 = findorbit4(RING,dp0);
fp = findorbit4(RING,dp0+ddp);
% Build initial condition vector that starts
% on the fixed point
X0dP = fp;
X0dP(5) = ddp;
X0dP(6) = 0;
X0 = [fp0;0;0];
% Track X0 for 1 turn
T = ringpass(RING,[X0 X0dP]);
% Calculate alpha
RingLength = findspos(RING,length(RING)+1);
a = (T(6,2)-T(6,1))/(ddp*RingLength);
GitHub Website at © 2018