Description of nus
nus
PURPOSE
NUS Computes synchrotron tune from RF parameters
SYNOPSIS
function Nus = nus (VrfMV, alpha, U0MeV, E0MeV, h)
DESCRIPTION
NUS Computes synchrotron tune from RF parameters
 Nus = nus (VrfMV, alpha, U0MeV, E0MeV, h)
 this function return the synchrotron tune
 input:
 VrfMV is the RF voltage in MV
 alpha is the momentum compaction factor
 U0MeV is the energy lost per turn in MeV
 E0MeV is the beam energy in MeV
 h is the harmonic number
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BunchLength bunch length due to the potential well effect
ringpara RINGPARA Calculates various ring parameters
calc_Touschek tauT = calc_Touschek(THERING, Ib)
calc_TouschekPM tauT = calc_TouschekPM(TD,dppPM,Trf,Ib,U0,coupling, sigE, emit_x)
Qval Qval gives the unitless Q parameter needed to compute the
SOURCE CODE
function Nus = nus (VrfMV, alpha, U0MeV, E0MeV, h)
%NUS Computes synchrotron tune from RF parameters
% Nus = nus (VrfMV, alpha, U0MeV, E0MeV, h)
% this function return the synchrotron tune
% input:
% VrfMV is the RF voltage in MV
% alpha is the momentum compaction factor
% U0MeV is the energy lost per turn in MeV
% E0MeV is the beam energy in MeV
% h is the harmonic number
Phi=pi - asin(U0MeV./VrfMV);
Nus= sqrt(-(VrfMV/E0MeV)*(h * alpha)/(2*pi) .* cos(Phi));
end
GitHub Website at © 2018