Description of atsigma
atsigma
PURPOSE
ATSIGMA constructs a beam sigma matrix 2x2 4x4 or 6x6
SYNOPSIS
function sigma = atsigma(varargin)
DESCRIPTION
ATSIGMA constructs a beam sigma matrix 2x2 4x4 or 6x6
   SIGMA=ATSIGMA(BETA,ALPHA,EMIT)
       builds a 2x2 sigma matrix for a transverse plane
   SIGMA=ATSIGMA(ESPREAD,BLENGTH)
       builds a 2x2 sigma matrix for the longitudinal plane
   SIGMA=ATSIGMA(BETAX,ALPHAX,EMITX,BETAZ,ALPHAZ,EMITZ)
       builds a 4x4 sigma matrix
   SIGMA=ATSIGMA(BETAX,ALPHAX,EMITX,BETAZ,ALPHAZ,EMITZ,ESPREAD,BLENGTH)
       builds a 6x6 sigma matrix
   SIGMA=ATSIGMA(ATSTRUCT)
       builds a 6x6 sigma matrix
  See also atx
CROSS-REFERENCE INFORMATION
This function calls:
atsigma ATSIGMA constructs a beam sigma matrix 2x2 4x4 or 6x6
atx ATX Computes and displays global information
blength
This function is called by:
testTrackBBR create a fast ring from ESRF lattice
atsigma ATSIGMA constructs a beam sigma matrix 2x2 4x4 or 6x6
SOURCE CODE
function sigma = atsigma(varargin)
%ATSIGMA constructs a beam sigma matrix 2x2 4x4 or 6x6
%
%   SIGMA=ATSIGMA(BETA,ALPHA,EMIT)
%       builds a 2x2 sigma matrix for a transverse plane
%
%   SIGMA=ATSIGMA(ESPREAD,BLENGTH)
%       builds a 2x2 sigma matrix for the longitudinal plane
%
%   SIGMA=ATSIGMA(BETAX,ALPHAX,EMITX,BETAZ,ALPHAZ,EMITZ)
%       builds a 4x4 sigma matrix
%
%   SIGMA=ATSIGMA(BETAX,ALPHAX,EMITX,BETAZ,ALPHAZ,EMITZ,ESPREAD,BLENGTH)
%       builds a 6x6 sigma matrix
%
%   SIGMA=ATSIGMA(ATSTRUCT)
%       builds a 6x6 sigma matrix
%
%  See also atx
if iscell(varargin{1})
    beamdata=atx(varargin{1},0,1);
    sigma=beamdata(1).beam66;
elseif nargin == 2
    [espread,blength]=deal(varargin{:});
    sigma=[espread.*espread 0;0 blength.*blength];
elseif nargin == 3
    [bx,ax,epsx]=deal(varargin{:});
    sigma=epsx*[bx -ax;-ax (1+ax*ax)/bx];
elseif nargin == 6
    [bx,ax,epsx,bz,az,epsz]=deal(varargin{:});
    sigma=[atsigma(bx,ax,epsx) zeros(2,2);...
        zeros(2,2) atsigma(bz,az,epsz)];
else
    [bx,ax,epsx,bz,az,epsz,espread,blength]=deal(varargin{:});
    sigma=[atsigma(bx,ax,epsx) zeros(2,4);...
        zeros(2,2) atsigma(bz,az,epsz) zeros(2,2);...
        zeros(2,4) atsigma(espread,blength)];
end
end
GitHub Website at © 2018