# theme: jekyll-theme-cayman
theme: minima
title: Accelerator Toolbox
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A toolbox for modelling particle accelerators in Matlab or python

kramdown:
  math_engine: mathjax
