Description of ele2at_run_me
ele2at_run_me
PURPOSE
test_elegant_converter
SYNOPSIS
This is a script file.
DESCRIPTION
test_elegant_converter
CROSS-REFERENCE INFORMATION
This function calls:
plotbeta PLOTBETA plots UNCOUPLED! beta-functions
atplot ATPLOT Plots optical functions
elegant2at function elegant2at(elegantlattice,E0,outfilename)
This function is called by:
SOURCE CODE
%test_elegant_converter
elegant2at('test.new',3);
load test_AT.mat;
atplot(THERING);
try
    plotbeta;
catch
    disp('elegant 2 at conversion unsuccessful. Check if files are in the right folder');
end
GitHub Website at © 2018