Description of atdynap
atdynap
PURPOSE
ATDYNAP Computes the dynamic aperture for ring structure
SYNOPSIS
function [xx,zz]=atdynap(ring,nt,dpp,rfrac)
DESCRIPTION
ATDYNAP Computes the dynamic aperture for ring structure
  [xx,zz] = atdynap(ring,nturns,dpp,rfrac)
  INPUTS
  1. ring  - Lattice strucutre
  2. nt    - Number of turns for tracking
  3. dpp   - Energy offset (default: 0)
  4. rfrac - Resolution of the grid for checking the stability
              as a fraction of the maximum stable amplitude
              (default: 0.02)
  OUPUTS
  1. XX - Horizontal limit of the dynamic aperture (betatron amplitudes in m)
  2. ZZ - Vertical limit of the dynamic aperture (betatron amplitudes in m)
  NOTES
  1. Algorithm in 2 steps
  2. Speed up possible using a alorithm similar to ELEGANT with dichotomy
  3. Improve and add more input parameter for rlist and np at least
  4. Handle DISPLAYFLAG
  EXAMPLES
  1. ring = soleil; % load lattice
     [xx zz] = atdynap(ring, 100); % compute DA
     plot(xx,zz, '*-'); % plot DA
  See also atmomap
CROSS-REFERENCE INFORMATION
This function calls:
findorbit4 FINDORBIT4 finds closed orbit in the 4-d transverse phase
findorbit6 FINDORBIT6 finds closed orbit in the full 6-d phase space
ringpass RINGPASS tracks particles through each element of the cell array RING
This function is called by:
SUBFUNCTIONS
function rmax=ascan(ring,nt,clorb,theta,rlist, DISPLAYFLAG)
function [xmax,zmax]=bscan(ring,nt,clorb,xlist,zlist, DISPLAYFLAG)
SOURCE CODE
function [xx,zz]=atdynap(ring,nt,dpp,rfrac)
%ATDYNAP Computes the dynamic aperture for ring structure
%
%  [xx,zz] = atdynap(ring,nturns,dpp,rfrac)
%
%  INPUTS
%  1. ring  - Lattice strucutre
%  2. nt    - Number of turns for tracking
%  3. dpp   - Energy offset (default: 0)
%  4. rfrac - Resolution of the grid for checking the stability
%              as a fraction of the maximum stable amplitude
%              (default: 0.02)
%  OUPUTS
%  1. XX - Horizontal limit of the dynamic aperture (betatron amplitudes in m)
%  2. ZZ - Vertical limit of the dynamic aperture (betatron amplitudes in m)
%
%  NOTES
%  1. Algorithm in 2 steps
%  2. Speed up possible using a alorithm similar to ELEGANT with dichotomy
%  3. Improve and add more input parameter for rlist and np at least
%  4. Handle DISPLAYFLAG
%
%  EXAMPLES
%  1. ring = soleil; % load lattice
%     [xx zz] = atdynap(ring, 100); % compute DA
%     plot(xx,zz, '*-'); % plot DA
%
%  See also atmomap
DISPLAYFLAG = 1;
np=5; % number of point. The sampling over pi will be in 2np+3 points
rlist=0:0.001:0.1; %
if nargin < 4, rfrac=0.02; end
if nargin < 3, dpp=0.0; end
% closed orbit 6D if on momentum
if isnumeric(dpp)
    clorb=[findorbit4(ring,dpp);dpp;0];
else
    clorb=findorbit6(ring);
end
t1=linspace(0,pi,2*np+3);
% Border theta=0,pi/é,pi fast exploration
% looks for xmax/z=0
xpmax = ascan(ring,nt,clorb,0,rlist, DISPLAYFLAG);
% looks for zmax/x=0
zmax  = ascan(ring,nt,clorb,0.5*pi,rlist, DISPLAYFLAG);
% looks for xmin/z=0
xmmax = ascan(ring,nt,clorb,pi,rlist, DISPLAYFLAG);
%
% x1=[xpmax*ones(1,np+2) xmmax*ones(1,np+1)];
% z1=zmax*ones(1,2*np+3);
% tlist=atan2(sin(t1).*z1,cos(t1).*x1)';
%
% rr=NaN(2*np+3,1);
% rr(1)=xpmax;
% rr(np+2)=zmax;
% rr(2*np+3)=xmmax;
% for i=[2:np+1 np+3:2*np+2]
%    rr(i)=ascan(ring,nt,clorb,tlist(i),rlist);
% end
% xx=rr.*cos(tlist);
% zz=rr.*sin(tlist);
% Real search for DA between 0.5 and 2 time maximum found at the previous
% iteration
slist=0.5:rfrac:2;
xx=NaN(2*np+3,1);
zz=xx;
% Positive DA
for i=1:np+3
    [xx(i),zz(i)]=bscan(ring,nt,clorb,...
        xpmax*cos(t1(i))*slist,zmax*sin(t1(i))*slist, DISPLAYFLAG);
end
% Negative DA
for i=np+4:2*np+3
    [xx(i),zz(i)]=bscan(ring,nt,clorb,...
        xmmax*cos(t1(i))*slist,zmax*sin(t1(i))*slist, DISPLAYFLAG);
end
function rmax=ascan(ring,nt,clorb,theta,rlist, DISPLAYFLAG)
%ASCAN Looks for DA around closed orbit
%
%  INPUTS
%  1. ring  - Ring lattice
%  2. nt    - Number of turns
%  3. clorb - Closed orbit
%  4. theta - Vector of angle (defining a radius) for the sampling of DA
%  5. rlist - Number of points to search for on each radius
%
%  OUPUTS
%  1. rmax - Maximum radius
for rr=rlist
    rin=clorb+[rr*cos(theta);0;rr*sin(theta);0;0;0];
    [dummy,lost]=ringpass(ring,rin,nt,'KeepLattice'); %#ok<ASGLU>
    if lost, break; end
    rmax=rr;
end
if DISPLAYFLAG
    fprintf('theta: %g, r: %g\n',theta,rmax);
end
function [xmax,zmax]=bscan(ring,nt,clorb,xlist,zlist, DISPLAYFLAG)
%BSCAN Looks for DA around closed orbit
%
%  INPUTS
%  1. ring  - Ring lattice
%  2. nt    - Number of turns
%  3. clorb - Closed orbit
%  4. xlist - Vector of horizontal points
%  5. zlist - Vector of vertical points
%
%  OUPUTS
%  1. xmax - Vector horizontal points defining the border of the DA
%  2. zmax - Vector vertical points defining the border of the DA
xmax = 0.0;
zmax = 0.0;
for i=1:length(xlist)
    rin=clorb+[xlist(i);0;zlist(i);0;0;0];
    [dummy,lost]=ringpass(ring,rin,nt,'KeepLattice'); %#ok<ASGLU>
    if lost, break; end
    xmax=xlist(i);
    zmax=zlist(i);
end
if DISPLAYFLAG
    fprintf('xm: %g, zm: %g\n',xmax,zmax);
end