Description of setBpmOffsetOnDipoleRef
setBpmOffsetOnDipoleRef
PURPOSE
% set bpm on curve defined by dipole misalignments
SYNOPSIS
function rerr=setBpmOffsetOnDipoleRef(rerr)
DESCRIPTION
 % set bpm on curve defined by dipole misalignments
see also: ApplyErrorsRand
CROSS-REFERENCE INFORMATION
This function calls:
findspos FINDSPOS returns longitudinal positions of accelerator lattice elements.
findcells FINDCELLS performs a search on MATLAB cell arrays of structures
setcellstruct SETCELLSTRUCT sets the field values of MATLAB cell array of structures
GetExistingErrors this function retrives 6 vectors, for x, y,s misalignments,
This function is called by:
SOURCE CODE
function rerr=setBpmOffsetOnDipoleRef(rerr)
% % set bpm on curve defined by dipole misalignments
%
%see also: ApplyErrorsRand
inddip=findcells(rerr,'BendingAngle');
indbpm=findcells(rerr,'Class','Monitor');
[X,Y,~,T,~,~,bpmerr]=GetExistingErrors(rerr,inddip);
indbpm=[indbpm(end) indbpm indbpm(1)]; % last and first bpm
sposBPM=findspos(rerr,indbpm);
sposDip=findspos(rerr,inddip);
offx=interp1(sposDip,X,sposBPM);offx(isnan(offx))=0;
offy=interp1(sposDip,Y,sposBPM);offy(isnan(offy))=0;
offr=interp1(sposDip,T,sposBPM);offr(isnan(offr))=0;
rerr=setcellstruct(rerr,'Offset',indbpm(2:end-1),bpmerr.offsetx-offx(2:end-1),1,1);
rerr=setcellstruct(rerr,'Offset',indbpm(2:end-1),bpmerr.offsetx-offy(2:end-1),1,2);
rerr=setcellstruct(rerr,'Rotation',indbpm(2:end-1),bpmerr.rotation-offr(2:end-1)*0,1,1);% NO ROTATION!! *0
disp('BPMs on dipole positions curve');
return